# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
